version: '3.9'

services:
  fastapi_template:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DB_URL}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge